# Integration tests for get_power_generation() using fixture CSVs and mocked
# data-fetching bindings. The fixtures live in tests/testthat/fixtures/ and are
# generated by tests/testthat/fixtures/build-power-fixtures.R.
#
# Fixture countries:
#   DE  - normal scaling case; one planted MAD outlier (2024-06 Solar);
#         Ember yearly is monthly_sum * 1.04 so the yearly correction is visible
#   CY  - Ember-only (no ENTSOE rows)
#   SI  - ENTSOE=0 Wind + Ember>0 Wind  (fallback path)
#         ENTSOE>0 Gas + Ember=0 Gas    (ratio=0 path)

library(testthat)
suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(lubridate)
})

load_fixtures <- function() {
  list(
    entsoe_daily  = read_csv(test_path("fixtures/power_entsoe_daily.csv"),
                             col_types = cols(date = col_date(), .default = col_guess())),
    ember_monthly = read_csv(test_path("fixtures/power_ember_monthly.csv"),
                             col_types = cols(date = col_date(), .default = col_guess())),
    ember_yearly  = read_csv(test_path("fixtures/power_ember_yearly.csv"),
                             col_types = cols(date = col_date(), .default = col_guess()))
  )
}

# Helper to run the pipeline with mocked fetches.
run_pipeline <- function(fx, iso2s = c("DE", "CY", "SI"),
                         date_from = "2023-01-01",
                         date_to   = "2024-12-31") {
  local_mocked_bindings(
    entsoe.get_power_generation = function(date_from, date_to, iso2s, ...) {
      fx$entsoe_daily %>%
        filter(iso2 %in% !!iso2s,
               date >= as.Date(date_from),
               date <= as.Date(date_to))
    },
    ember.get_power_generation = function(frequency, iso2s, ...) {
      df <- if (frequency == "monthly") fx$ember_monthly else fx$ember_yearly
      df %>% filter(iso2 %in% !!iso2s)
    }
  )

  get_power_generation(
    iso2s              = iso2s,
    date_from          = date_from,
    date_to            = date_to,
    use_cache          = FALSE,
    diagnostics_folder = NULL
  )
}

# ============================================================================
# 7. Monthly conservation invariant
# ============================================================================

test_that("monthly sum of scaled output matches Ember_monthly * yearly_correction", {
  fx <- load_fixtures()
  res <- run_pipeline(fx, iso2s = "DE")

  # Aggregate scaled to monthly per Ember-named source
  scaled_monthly <- res %>%
    filter(source != "Total") %>%
    mutate(ymd = floor_date(date, "month"),
           ember_source = recode(source, "Fossil Gas" = "Gas")) %>%
    group_by(iso2, ember_source, ymd) %>%
    summarise(scaled_mwh = sum(value_mwh), .groups = "drop")

  # Build the true target = ember_monthly * yearly_correction
  yearly_corr <- fx$ember_yearly %>%
    mutate(year = year(date)) %>%
    select(iso2, source, year, ember_yearly = value_mwh) %>%
    inner_join(
      fx$ember_monthly %>%
        mutate(year = year(date)) %>%
        group_by(iso2, source, year) %>%
        summarise(monthly_sum = sum(value_mwh), .groups = "drop"),
      by = c("iso2", "source", "year")
    ) %>%
    mutate(ratio_y = ember_yearly / monthly_sum) %>%
    select(iso2, source, year, ratio_y)

  target <- fx$ember_monthly %>%
    filter(iso2 == "DE") %>%
    mutate(year = year(date)) %>%
    left_join(yearly_corr, by = c("iso2", "source", "year")) %>%
    mutate(target_mwh = value_mwh * ratio_y) %>%
    select(iso2, ember_source = source, ymd = date, target_mwh)

  cmp <- inner_join(scaled_monthly, target,
                    by = c("iso2", "ember_source", "ymd"))

  # All months should match within 1e-6 relative
  cmp <- cmp %>% filter(target_mwh > 0) %>%
    mutate(rel_err = abs(scaled_mwh - target_mwh) / target_mwh)
  expect_true(all(cmp$rel_err < 1e-6))
})

# ============================================================================
# 8. Yearly conservation invariant
# ============================================================================

test_that("yearly sum of scaled output matches Ember_yearly", {
  fx <- load_fixtures()
  res <- run_pipeline(fx, iso2s = "DE")

  scaled_yearly <- res %>%
    filter(source != "Total") %>%
    mutate(year = year(date),
           ember_source = recode(source, "Fossil Gas" = "Gas")) %>%
    group_by(iso2, ember_source, year) %>%
    summarise(scaled = sum(value_mwh), .groups = "drop")

  ember_yearly_de <- fx$ember_yearly %>%
    filter(iso2 == "DE") %>%
    mutate(year = year(date)) %>%
    select(iso2, ember_source = source, year, ember = value_mwh)

  cmp <- inner_join(scaled_yearly, ember_yearly_de,
                    by = c("iso2", "ember_source", "year")) %>%
    filter(ember > 0) %>%
    mutate(rel_err = abs(scaled - ember) / ember)

  expect_true(all(cmp$rel_err < 1e-6))
})

# ============================================================================
# 9. Output schema
# ============================================================================

test_that("output has exact expected columns and uses legacy source names", {
  fx <- load_fixtures()
  res <- run_pipeline(fx)

  expect_equal(sort(colnames(res)),
               sort(c("iso2", "country", "region", "date", "source",
                      "value_mw", "value_mwh")))

  # Source remap: "Gas" must be remapped to "Fossil Gas", "Other Renewables" to "Other"
  expect_true("Fossil Gas" %in% res$source)
  expect_false("Gas" %in% res$source)
})

# ============================================================================
# 10. No duplicate (iso2, source, date) rows
# ============================================================================

test_that("output has unique (iso2, source, date) rows", {
  fx <- load_fixtures()
  res <- run_pipeline(fx)

  dups <- res %>% group_by(iso2, source, date) %>% filter(n() > 1) %>% nrow()
  expect_equal(dups, 0L)
})

# ============================================================================
# 11. date_from / date_to filter
# ============================================================================

test_that("output respects date_from and date_to bounds", {
  fx <- load_fixtures()
  res <- run_pipeline(fx,
                      date_from = "2024-03-15",
                      date_to   = "2024-08-15")

  expect_gte(min(res$date), as.Date("2024-03-15"))
  expect_lte(max(res$date), as.Date("2024-08-15"))
})

# ============================================================================
# 12. Ember-only fallback (CY)
# ============================================================================

test_that("Ember-only country (CY) is in output with correct annual totals", {
  fx <- load_fixtures()
  res <- run_pipeline(fx, iso2s = "CY")

  # CY should have all three sources represented
  expect_setequal(
    unique(res$source[res$source != "Total"]),
    c("Wind", "Solar", "Fossil Gas")
  )

  # Annual total matches Ember yearly
  scaled_yearly <- res %>%
    filter(source != "Total") %>%
    mutate(year = year(date),
           ember_source = recode(source, "Fossil Gas" = "Gas")) %>%
    group_by(ember_source, year) %>%
    summarise(scaled = sum(value_mwh), .groups = "drop")

  ember_yearly_cy <- fx$ember_yearly %>%
    filter(iso2 == "CY") %>%
    mutate(year = year(date)) %>%
    select(ember_source = source, year, ember = value_mwh)

  cmp <- inner_join(scaled_yearly, ember_yearly_cy,
                    by = c("ember_source", "year")) %>%
    mutate(rel_err = abs(scaled - ember) / ember)

  expect_true(all(cmp$rel_err < 1e-6))
})

# ============================================================================
# 13. SI Wind: ENTSOE=0 + Ember>0 routes through fallback (output > 0)
# ============================================================================

test_that("SI Wind (ENTSOE=0, Ember>0) routed through fallback gives non-zero output", {
  fx <- load_fixtures()
  res <- run_pipeline(fx, iso2s = "SI")

  si_wind_total <- res %>%
    filter(iso2 == "SI", source == "Wind") %>%
    pull(value_mwh) %>%
    sum()

  # Ember reports 60 * days_in_month MWh/month - SI fallback should reproduce
  # this annually (within yearly correction; here ratio_y = 1).
  ember_wind_total <- fx$ember_yearly %>%
    filter(iso2 == "SI", source == "Wind") %>%
    summarise(t = sum(value_mwh)) %>% pull(t)

  expect_gt(si_wind_total, 0)
  expect_lt(abs(si_wind_total - ember_wind_total) / ember_wind_total, 1e-6)
})

# ============================================================================
# 14. SI Gas: ENTSOE>0 + Ember=0 produces zero output
# ============================================================================

test_that("SI Gas (ENTSOE>0, Ember=0) produces exactly zero scaled output", {
  fx <- load_fixtures()
  res <- run_pipeline(fx, iso2s = "SI")

  si_gas_total <- res %>%
    filter(iso2 == "SI", source == "Fossil Gas") %>%
    pull(value_mwh) %>%
    sum()

  expect_equal(si_gas_total, 0)
})

# ============================================================================
# 15. Hydro Pumped Storage excluded
# ============================================================================

test_that("Hydro Pumped Storage source rows in input are not in output", {
  fx <- load_fixtures()
  # Inject HPS rows for DE
  fx$entsoe_daily <- bind_rows(
    fx$entsoe_daily,
    expand.grid(
      iso2 = "DE", region = "Europe", country = "Germany",
      source = "Hydro Pumped Storage",
      date = seq.Date(as.Date("2024-01-01"), as.Date("2024-01-31"), by = "day"),
      stringsAsFactors = FALSE
    ) %>%
      mutate(value_mwh = 100, value_mw = 100 / 24, data_source = "entsoe")
  )

  res <- run_pipeline(fx, iso2s = "DE")
  expect_false("Hydro Pumped Storage" %in% res$source)
})
