# Sectors
SECTOR_ELEC <- "electricity"
SECTOR_ALL <- "all"
SECTOR_OTHERS <- "others"

SECTOR_TRANSPORT <- "transport"
SECTOR_TRANSPORT_DOMESTIC <- "transport_domestic"
SECTOR_TRANSPORT_INTERNATIONAL_AVIATION <- "transport_international_aviation"
SECTOR_TRANSPORT_INTERNATIONAL_SHIPPING <- "transport_international_shipping"

# Fuel families
FUEL_COAL <- "coal"
FUEL_COKE <- "coke"
FUEL_PEAT <- "peat"
FUEL_OIL <- "oil"
FUEL_GAS <- "gas"
FUEL_TOTAL <- "total"

# SIEC code for Eurostat

## Oil products
SIEC_OIL_PRODUCTS <- "O4600"
SIEC_CRUDE_OIL <- "O4100_TOT_4200-4500"
SIEC_GASOIL_DIESEL <- "O4671"
SIEC_FUEL_OIL <- "O4680"
SIEC_HEATING_GASOIL <- "O46712"
SIEC_ROAD_DIESEL <- "O46711"
SIEC_MOTOR_GASOLINE_XBIO <- "O4652XR5210B"
SIEC_KEROSENE_XBIO <- "O4661XR5230B"
SIEC_AVIATION_GASOLINE <- "O4651"
SIEC_BIOGASOLINE <- "R5210B"
SIEC_BIODIESEL <- "R5220B"

## Solid fuels
SIEC_BROWN_COAL <- "C0200"
SIEC_HARD_COAL <- "C0100"
SIEC_COKE_OVEN_COKE <- "C0311"
SIEC_BROWN_COAL_BRIQUETTES <- "C0330"
SIEC_OIL_SHALE <- "S2000"
SIEC_PEAT <- "P1100"

HARDCOAL_COKING_RATE_FACTOR <- 0.08 # See investigate_coking_emissions

## Gas
SIEC_NATURAL_GAS <- "G3000"
SIEC_COKE_OVEN_GAS <- "C0350"


# Conversion factors
gcv_kwh_m3 <- 11.3505
ncv_kwh_m3 <- gcv_kwh_m3 / 1.108
ncv_gcv_gas <- 0.9
